<?php

use Illuminate\Database\Seeder;
use App\Region;
use App\Country;

class LocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        
    	$cr_1 = new Country(['name' => 'Белоруссия (Беларусь)', 'iso_code_2' => 'BY', 'iso_code_3' => 'BLR']);
    	$cr_1->save();
    	$cr_2 = new Country(['name' => 'Грузия', 'iso_code_2' => 'GE', 'iso_code_3' => 'GEO']);
    	$cr_2->save();
    	$cr_3 = new Country(['name' => 'Казахстан', 'iso_code_2' => 'KZ', 'iso_code_3' => 'KAZ']);
    	$cr_3->save();
    	$cr_4 = new Country(['name' => 'Киргизия (Кыргызстан)', 'iso_code_2' => 'KG', 'iso_code_3' => 'KGZ']);
    	$cr_4->save();
    	$cr_5 = new Country(['name' => 'Российская Федерация', 'iso_code_2' => 'RU', 'iso_code_3' => 'RUS']);
    	$cr_5->save();
    	$cr_6 = new Country(['name' => 'Украина', 'iso_code_2' => 'UA', 'iso_code_3' => 'UKR']);
    	$cr_6->save();
    	$cr_7 = new Country(['name' => 'Узбекистан', 'iso_code_2' => 'UZ', 'iso_code_3' => 'UZB']);
    	$cr_7->save();


		$reg = new Region(['country_id' => 1, 'name' => 'Брест', 'code' => 'BR']);
$reg->save();
		$reg = new Region(['country_id' => 1, 'name' => 'Гомель', 'code' => 'HO']);
$reg->save();
		$reg = new Region(['country_id' => 1, 'name' => 'Минск', 'code' => 'HM']);
$reg->save();
		$reg = new Region(['country_id' => 1, 'name' => 'Гродно', 'code' => 'HR']);
$reg->save();
		$reg = new Region(['country_id' => 1, 'name' => 'Могилев', 'code' => 'MA']);
$reg->save();
		$reg = new Region(['country_id' => 1, 'name' => 'Минская область', 'code' => 'MI']);
$reg->save();
		$reg = new Region(['country_id' => 1, 'name' => 'Витебск', 'code' => 'VI']);
$reg->save();
		$reg = new Region(['country_id' => 2, 'name' => 'Abkhazia', 'code' => 'AB']);
$reg->save();
		$reg = new Region(['country_id' => 2, 'name' => 'Ajaria', 'code' => 'AJ']);
$reg->save();
		$reg = new Region(['country_id' => 2, 'name' => 'Tbilisi', 'code' => 'TB']);
$reg->save();
		$reg = new Region(['country_id' => 2, 'name' => 'Guria', 'code' => 'GU']);
$reg->save();
		$reg = new Region(['country_id' => 2, 'name' => 'Imereti', 'code' => 'IM']);
$reg->save();
		$reg = new Region(['country_id' => 2, 'name' => 'Kakheti', 'code' => 'KA']);
$reg->save();
		$reg = new Region(['country_id' => 2, 'name' => 'Kvemo Kartli', 'code' => 'KK']);
$reg->save();
		$reg = new Region(['country_id' => 2, 'name' => 'Mtskheta-Mtianeti', 'code' => 'MM']);
$reg->save();
		$reg = new Region(['country_id' => 2, 'name' => 'Racha Lechkhumi and Kvemo Svanet', 'code' => 'RL']);
$reg->save();
		$reg = new Region(['country_id' => 2, 'name' => 'Samegrelo-Zemo Svaneti', 'code' => 'SZ']);
$reg->save();
		$reg = new Region(['country_id' => 2, 'name' => 'Samtskhe-Javakheti', 'code' => 'SJ']);
$reg->save();
		$reg = new Region(['country_id' => 2, 'name' => 'Shida Kartli', 'code' => 'SK']);
$reg->save();
		$reg = new Region(['country_id' => 3, 'name' => 'Алматинская область', 'code' => 'AL']);
$reg->save();
		$reg = new Region(['country_id' => 3, 'name' => 'Алматы - город республ-го значения', 'code' => 'AC']);
$reg->save();
		$reg = new Region(['country_id' => 3, 'name' => 'Акмолинская область', 'code' => 'AM']);
$reg->save();
		$reg = new Region(['country_id' => 3, 'name' => 'Актюбинская область', 'code' => 'AQ']);
$reg->save();
		$reg = new Region(['country_id' => 3, 'name' => 'Астана - город республ-го значения', 'code' => 'AS']);
$reg->save();
		$reg = new Region(['country_id' => 3, 'name' => 'Атырауская область', 'code' => 'AT']);
$reg->save();
		$reg = new Region(['country_id' => 3, 'name' => 'Западно-Казахстанская область', 'code' => 'BA']);
$reg->save();
		$reg = new Region(['country_id' => 3, 'name' => 'Байконур - город республ-го значения', 'code' => 'BY']);
$reg->save();
		$reg = new Region(['country_id' => 3, 'name' => 'Мангистауская область', 'code' => 'MA']);
$reg->save();
		$reg = new Region(['country_id' => 3, 'name' => 'Южно-Казахстанская область', 'code' => 'ON']);
$reg->save();
		$reg = new Region(['country_id' => 3, 'name' => 'Павлодарская область', 'code' => 'PA']);
$reg->save();
		$reg = new Region(['country_id' => 3, 'name' => 'Карагандинская область', 'code' => 'QA']);
$reg->save();
		$reg = new Region(['country_id' => 3, 'name' => 'Костанайская область', 'code' => 'QO']);
$reg->save();
		$reg = new Region(['country_id' => 3, 'name' => 'Кызылординская область', 'code' => 'QY']);
$reg->save();
		$reg = new Region(['country_id' => 3, 'name' => 'Восточно-Казахстанская область', 'code' => 'SH']);
$reg->save();
		$reg = new Region(['country_id' => 3, 'name' => 'Северо-Казахстанская область', 'code' => 'SO']);
$reg->save();
		$reg = new Region(['country_id' => 3, 'name' => 'Жамбылская область', 'code' => 'ZH']);
$reg->save();
		$reg = new Region(['country_id' => 4, 'name' => 'Bishkek', 'code' => 'GB']);
$reg->save();
		$reg = new Region(['country_id' => 4, 'name' => 'Batken', 'code' => 'B']);
$reg->save();
		$reg = new Region(['country_id' => 4, 'name' => 'Chu', 'code' => 'C']);
$reg->save();
		$reg = new Region(['country_id' => 4, 'name' => 'Jalal-Abad', 'code' => 'J']);
$reg->save();
		$reg = new Region(['country_id' => 4, 'name' => 'Naryn', 'code' => 'N']);
$reg->save();
		$reg = new Region(['country_id' => 4, 'name' => 'Osh', 'code' => 'O']);
$reg->save();
		$reg = new Region(['country_id' => 4, 'name' => 'Talas', 'code' => 'T']);
$reg->save();
		$reg = new Region(['country_id' => 4, 'name' => 'Ysyk-Kol', 'code' => 'Y']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Республика Хакасия', 'code' => 'KK']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Московская область', 'code' => 'MOS']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Чукотский АО', 'code' => 'CHU']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Архангельская область', 'code' => 'ARK']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Астраханская область', 'code' => 'AST']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Алтайский край', 'code' => 'ALT']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Белгородская область', 'code' => 'BEL']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Еврейская АО', 'code' => 'YEV']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Амурская область', 'code' => 'AMU']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Брянская область', 'code' => 'BRY']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Чувашская Республика', 'code' => 'CU']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Челябинская область', 'code' => 'CHE']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Карачаево-Черкесия', 'code' => 'KC']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Забайкальский край', 'code' => 'ZAB']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Ленинградская область', 'code' => 'LEN']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Республика Калмыкия', 'code' => 'KL']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Сахалинская область', 'code' => 'SAK']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Республика Алтай', 'code' => 'AL']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Чеченская Республика', 'code' => 'CE']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Иркутская область', 'code' => 'IRK']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Ивановская область', 'code' => 'IVA']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Удмуртская Республика', 'code' => 'UD']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Калининградская область', 'code' => 'KGD']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Калужская область', 'code' => 'KLU']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Республика Татарстан', 'code' => 'TA']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Кемеровская область', 'code' => 'KEM']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Хабаровский край', 'code' => 'KHA']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Ханты-Мансийский АО - Югра', 'code' => 'KHM']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Костромская область', 'code' => 'KOS']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Краснодарский край', 'code' => 'KDA']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Красноярский край', 'code' => 'KYA']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Курганская область', 'code' => 'KGN']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Курская область', 'code' => 'KRS']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Республика Тыва', 'code' => 'TY']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Липецкая область', 'code' => 'LIP']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Магаданская область', 'code' => 'MAG']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Республика Дагестан', 'code' => 'DA']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Республика Адыгея', 'code' => 'AD']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Москва', 'code' => 'MOW']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Мурманская область', 'code' => 'MUR']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Республика Кабардино-Балкария', 'code' => 'KB']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Ненецкий АО', 'code' => 'NEN']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Республика Ингушетия', 'code' => 'IN']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Нижегородская область', 'code' => 'NIZ']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Новгородская область', 'code' => 'NGR']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Новосибирская область', 'code' => 'NVS']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Омская область', 'code' => 'OMS']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Орловская область', 'code' => 'ORL']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Оренбургская область', 'code' => 'ORE']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Пензенская область', 'code' => 'PNZ']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Пермский край', 'code' => 'PER']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Камчатский край', 'code' => 'KAM']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Республика Карелия', 'code' => 'KR']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Псковская область', 'code' => 'PSK']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Ростовская область', 'code' => 'ROS']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Рязанская область', 'code' => 'RYA']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Ямало-Ненецкий АО', 'code' => 'YAN']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Самарская область', 'code' => 'SAM']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Республика Мордовия', 'code' => 'MO']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Саратовская область', 'code' => 'SAR']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Смоленская область', 'code' => 'SMO']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Санкт-Петербург', 'code' => 'SPE']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Ставропольский край', 'code' => 'STA']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Республика Коми', 'code' => 'KO']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Тамбовская область', 'code' => 'TAM']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Томская область', 'code' => 'TOM']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Тульская область', 'code' => 'TUL']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Тверская область', 'code' => 'TVE']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Тюменская область', 'code' => 'TYU']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Республика Башкортостан', 'code' => 'BA']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Ульяновская область', 'code' => 'ULY']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Республика Бурятия', 'code' => 'BU']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Республика Северная Осетия', 'code' => 'SE']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Владимирская область', 'code' => 'VLA']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Приморский край', 'code' => 'PRI']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Волгоградская область', 'code' => 'VGG']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Вологодская область', 'code' => 'VLG']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Воронежская область', 'code' => 'VOR']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Кировская область', 'code' => 'KIR']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Республика Саха', 'code' => 'SA']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Ярославская область', 'code' => 'YAR']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Свердловская область', 'code' => 'SVE']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Республика Марий Эл', 'code' => 'ME']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Республика Крым', 'code' => 'CR']);
$reg->save();
		$reg = new Region(['country_id' => 6, 'name' => 'Черкассы', 'code' => 'CK']);
$reg->save();
		$reg = new Region(['country_id' => 6, 'name' => 'Чернигов', 'code' => 'CH']);
$reg->save();
		$reg = new Region(['country_id' => 6, 'name' => 'Черновцы', 'code' => 'CV']);
$reg->save();
		$reg = new Region(['country_id' => 6, 'name' => 'Днепропетровск', 'code' => 'DN']);
$reg->save();
		$reg = new Region(['country_id' => 6, 'name' => 'Донецк', 'code' => 'DO']);
$reg->save();
		$reg = new Region(['country_id' => 6, 'name' => 'Ивано-Франковск', 'code' => 'IV']);
$reg->save();
		$reg = new Region(['country_id' => 6, 'name' => 'Харьков', 'code' => 'KH']);
$reg->save();
		$reg = new Region(['country_id' => 6, 'name' => 'Хмельницкий', 'code' => 'KM']);
$reg->save();
		$reg = new Region(['country_id' => 6, 'name' => 'Кировоград', 'code' => 'KR']);
$reg->save();
		$reg = new Region(['country_id' => 6, 'name' => 'Киевская область', 'code' => 'KV']);
$reg->save();
		$reg = new Region(['country_id' => 6, 'name' => 'Киев', 'code' => 'KY']);
$reg->save();
		$reg = new Region(['country_id' => 6, 'name' => 'Луганск', 'code' => 'LU']);
$reg->save();
		$reg = new Region(['country_id' => 6, 'name' => 'Львов', 'code' => 'LV']);
$reg->save();
		$reg = new Region(['country_id' => 6, 'name' => 'Николаев', 'code' => 'MY']);
$reg->save();
		$reg = new Region(['country_id' => 6, 'name' => 'Одесса', 'code' => 'OD']);
$reg->save();
		$reg = new Region(['country_id' => 6, 'name' => 'Полтава', 'code' => 'PO']);
$reg->save();
		$reg = new Region(['country_id' => 6, 'name' => 'Ровно', 'code' => 'RI']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Севастополь', 'code' => 'SEV']);
$reg->save();
		$reg = new Region(['country_id' => 6, 'name' => 'Сумы', 'code' => 'SU']);
$reg->save();
		$reg = new Region(['country_id' => 6, 'name' => 'Тернополь', 'code' => 'TE']);
$reg->save();
		$reg = new Region(['country_id' => 6, 'name' => 'Винница', 'code' => 'VI']);
$reg->save();
		$reg = new Region(['country_id' => 6, 'name' => 'Луцк', 'code' => 'VO']);
$reg->save();
		$reg = new Region(['country_id' => 6, 'name' => 'Ужгород', 'code' => 'ZK']);
$reg->save();
		$reg = new Region(['country_id' => 6, 'name' => 'Запорожье', 'code' => 'ZA']);
$reg->save();
		$reg = new Region(['country_id' => 6, 'name' => 'Житомир', 'code' => 'ZH']);
$reg->save();
		$reg = new Region(['country_id' => 6, 'name' => 'Херсон', 'code' => 'KE']);
$reg->save();
		$reg = new Region(['country_id' => 7, 'name' => 'Andijon', 'code' => 'AN']);
$reg->save();
		$reg = new Region(['country_id' => 7, 'name' => 'Buxoro', 'code' => 'BU']);
$reg->save();
		$reg = new Region(['country_id' => 7, 'name' => 'Farg\'ona', 'code' => 'FA']);
$reg->save();
		$reg = new Region(['country_id' => 7, 'name' => 'Jizzax', 'code' => 'JI']);
$reg->save();
		$reg = new Region(['country_id' => 7, 'name' => 'Namangan', 'code' => 'NG']);
$reg->save();
		$reg = new Region(['country_id' => 7, 'name' => 'Navoiy', 'code' => 'NW']);
$reg->save();
		$reg = new Region(['country_id' => 7, 'name' => 'Qashqadaryo', 'code' => 'QA']);
$reg->save();
		$reg = new Region(['country_id' => 7, 'name' => 'Qoraqalpog\'iston Republikasi', 'code' => 'QR']);
$reg->save();
		$reg = new Region(['country_id' => 7, 'name' => 'Samarqand', 'code' => 'SA']);
$reg->save();
		$reg = new Region(['country_id' => 7, 'name' => 'Sirdaryo', 'code' => 'SI']);
$reg->save();
		$reg = new Region(['country_id' => 7, 'name' => 'Surxondaryo', 'code' => 'SU']);
$reg->save();
		$reg = new Region(['country_id' => 7, 'name' => 'Toshkent City', 'code' => 'TK']);
$reg->save();
		$reg = new Region(['country_id' => 7, 'name' => 'Toshkent Region', 'code' => 'TO']);
$reg->save();
		$reg = new Region(['country_id' => 7, 'name' => 'Xorazm', 'code' => 'XO']);
$reg->save();
		$reg = new Region(['country_id' => 5, 'name' => 'Байконур - город республ-го значения', 'code' => 'BY']);
$reg->save();

    }
}
